nameOverride: ""
fullnameOverride: ""
timeout: 3m

csi:
  attacher:
    image:
      repository: k8s.gcr.io/sig-storage/csi-attacher
      tag: v2.2.1
      pullPolicy: IfNotPresent
  provisioner:
    image:
      repository: k8s.gcr.io/sig-storage/csi-provisioner
      tag: v1.6.1
      pullPolicy: IfNotPresent
  snapshotter:
    image:
      repository: k8s.gcr.io/sig-storage/csi-snapshotter
      tag: v2.1.3
      pullPolicy: IfNotPresent
  resizer:
    image:
      repository: k8s.gcr.io/sig-storage/csi-resizer
      tag: v0.5.1
      pullPolicy: IfNotPresent
  livenessprobe:
    image:
      repository: k8s.gcr.io/sig-storage/livenessprobe
      tag: v2.1.0
      pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    image:
      repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
      tag: v1.3.0
      pullPolicy: IfNotPresent
  plugin:
    image:
      repository: docker.io/k8scloudprovider/cinder-csi-plugin
      pullPolicy: IfNotPresent
      tag:  # defaults to .Chart.AppVersion
    volumes:
      - name: cacert
        hostPath:
          path: /etc/cacert
    volumeMounts:
      - name: cacert
        mountPath: /etc/cacert
        readOnly: true
      - name: cloud-config
        mountPath: /etc/kubernetes
        readOnly: true

secret:
  enabled: false
  create: false
#  name: cinder-csi-cloud-config
#  data:
#    cloud-config: |-
#      [Global]
#      auth-url=http://openstack-control-plane
#      user-id=user-id
#      password=password
#      trust-id=trust-id
#      region=RegionOne
#      ca-file=/etc/cacert/ca-bundle.crt

storageClass:
  enabled: true
  delete:
    isDefault: false
    allowVolumeExpansion: true
  retain:
    isDefault: false
    allowVolumeExpansion: true

priorityClassName:
  controllerPlugin: ""
  nodePlugin: ""

podSecurityPolicy:
  # Setting this to true will create a role and rolebinding granting the service accounts access to use the selected pod security policy
  enabled: false

  # Leave empty if you want the helm chart to create a pod security policy for you (and set create to true)
  # If not empty this should be the name of a pre-existing pod security policy resource deployed in the cluster (and set create to false)
  existingPolicyName: ""

  # Whether the helm chart should create a pod security policy
  create: false
